image: eclipse-temurin:21-jdk-alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GRADLE_USER_HOME: ".gradle"

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "feat/simulatorapi"

stages:
  - build
  - test

before_script:
  - chmod +x ./gradlew

build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week

test:
  stage: test
  script:
    - ./gradlew test
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml
    paths:
      - build/reports/tests/
      - build/test-results/
    expire_in: 1 week